name = "online-tv"
compatibility_date = "2024-01-01"

kv_namespaces = [
  { binding = "CHANNELS", id = "0eb71c2d219a4fef87749e14ee4f71f3" }
]

[site]
bucket = "./dist"

[env.production]
kv_namespaces = [
  { binding = "CHANNELS", id = "0eb71c2d219a4fef87749e14ee4f71f3" }
]

[triggers]
crons = ["0 3 * * *"]