name = "tv-channels-worker"
main = "worker/index.ts"
compatibility_date = "2024-01-01"

[vars]
CACHE_KEY = "tv_channels_cache"
IPV6_URL = "https://live.zbds.top/tv/iptv6.m3u"
IPV4_URL = "https://live.zbds.top/tv/iptv4.m3u"